apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: bot
spec:
  rules:
  - host: bot.fleur.ai
    http:
      paths:
      - path: /
        backend:
          serviceName: bot
          servicePort: 80
