apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bot
  labels:
    name: bot
    k8s-app: fleur
spec:
  replicas: 1
  revisionHistoryLimit: 5
  minReadySeconds: 20
  strategy:
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 2
  template:
    metadata:
      labels:
        name: bot
        k8s-app: fleur
    spec:
      containers:
      - name: fleur
        image: index.docker.io/blaaast/fleur:ae2b6970d1701bf0c596953adb747d231656d436
        env:
        - name: SLACK_TOKEN
          valueFrom:
            secretKeyRef:
              name: fleur-app-bot
              key: SLACK_TOKEN
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: fleur-app-bot
              key: REDIS_URL
        - name: NODE_ENV
          valueFrom:
            secretKeyRef:
              name: fleur-app-bot
              key: NODE_ENV
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 256Mi
        # This setting makes nodes pull the docker image every time before
        # starting the pod. This is useful when debugging, but should be turned
        # off in production.
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: docker-registry
---
apiVersion: v1
kind: Service
metadata:
  name: bot
  labels:
    name: bot
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    name: bot
